name = "SortedVectors"
uuid = "9404b2b5-64ac-5ade-85a3-77c836ef30b4"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"

[compat]
ArgCheck = "2"
DocStringExtensions = "0.8, 0.9"
julia = "1.8"
