name = "SortedVectors"
uuid = "9404b2b5-64ac-5ade-85a3-77c836ef30b4"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.3.1"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
ArgCheck = "2"
DocStringExtensions = "0.8, 0.9"
julia = "1.8"
